name: Build Lint Test Coverage

on:
  push:
    branches: [ main, "v*"]
  pull_request:
    branches: [ main, "v*"]

jobs:
  build-lint-test-coverage:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10", "3.11"]
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3
      - name: Get git tags
        run:  git fetch --prune --unshallow --tags
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip' # caching pip dependencies
      - name: Build and install
        run: pip install .
      # - name: Lint
      #   run: pre-commit run --all-files
      - name: Test
        run: pytest . # --cov --cov-report xml
      # - name: Coverage
      #   uses: coverallsapp/github-action@v2.0.0
      #   with:
      #     github-token: ${{ secrets.COVERALLS_TOKEN }}
      #     path-to-lcov: coverage.xml
